name: CI
on: [push]
jobs:
    e2e:
        name: 'Build + E2E tests'
        env:
            NODE_ENV: test
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 04

            - uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install deps (with cache)
              run: npm install

            - name: Install playwright
              run: npx playwright install chromium

            - name: Next.js cache
              uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-nextjs

            - name: Setup Prisma
              run: npm run db:generate

            - run: npm run db:populate
            - run: npm run build
            - run: npm run test-e2e

            - name: Check types
              run: npx tsc

            - name: Upload test results
              if: ${{ always() }}
              uses: actions/upload-artifact@v2
              with:
                  name: test results
                  path: |
                      playwright/test-results

    unit:
        name: 'Unit tests + typecheck'
        env:
            NODE_ENV: test
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: 'npm' # You can active this cache when your repo has a lockfile

            - name: Install deps (with cache)
              run: npm install

            - name: Next.js cache
              uses: actions/cache@v3
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-nextjs

            - name: Setup Prisma
              run: npm run db:generate

            - run: npm run db:populate
            - run: npm run test-unit
            - run: npx tsc